[package]
name = "lb-analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bacon = "2.13.0"
color-eyre = "0.6.2"
tokio = { version = "1.32.0", features = ["full"] }
whois-rust = "1.5.2"
